name: flutter_asset_optimizer
description: Find & remove unused assets + compress images automatically.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.5.0
  image: ^4.2.0
  path: ^1.9.0
  yaml: ^3.1.2

executables:
  flutter_asset_optimizer:

